#!/bin/bash

# Copyright (C) 2021 Timothe Litt <litt at acm.org>

# Check for non-empty quarantine queue & report

SMQ="`dirname $0`/smqdecode"
QD="/var/spool/mqueue"

if [ -x "$SMQ" -a -d "$QD" ]; then
    FOUND=0
    while read ; do
        if [ -z "$FOUND" ]; then echo "Quarantined e-mail"; fi
        echo
        ((FOUND++))

        # Extract queue ID

        echo "$QD/$REPLY => ${REPLY:2}"

        # Select interesting headers and indent

        $SMQ "$REPLY" | \
            grep -iP '^(From|Date|To|Subject|Message-ID|X-Virus-Status):' | \
            sed -e 's/^/    /g'
    done < <( find "$QD" -maxdepth 1 -type f -name "hf*" -printf '%f\n' )

    if [ $FOUND -gt 0 ]; then
        exit 0
    elif [ -z "$CRONJOB" ]; then
        echo "Quarantine is empty"
        exit 1
    else
        exit 1
    fi
fi

# Fallback to mailq

L="`mailq -qQ 2>&1`"
if [ -n "$CRONJOB" ] && echo "$L" | grep -qP '^\s*Total\srequests:\s+0'; then
    exit 0
fi

cat <<EOF
$L
EOF
