#!/bin/bash

# Copyright (C) 2021 Timothe Litt <litt at acm.org>

# Check for non-empty quarantine queue & report

SMQ="`dirname $0`/smqdecode"
QD="/var/spool/mqueue"

if [ -x "$SMQ" -a -d "$QD" ]; then
    FOUND=0
    while read ; do
        if [ "$FOUND" == 0 ]; then echo "Quarantined e-mail"; fi
        echo
        ((FOUND++))

        # Extract queue ID

        echo "$QD/$REPLY => ${REPLY:2}"

        # Select interesting headers and indent

        $SMQ --queue=$QD --headers --nobody --nowarn --nometadata "$REPLY" | \
            grep -iP '^(From|Date|To|Subject|Message-ID|X-Virus-Status):'  | \
            sed -e 's/^/    /g'

        # Command to view this e-mail

        echo "    View   : $SMQ --queue=$QD --message --limit-body=none ${REPLY:2} | less"

        # Command to remove from quarantine & delete immediately

        echo "    Delete : rm -f $QD/{d,h}${REPLY:1}"

        # Command to release from quarantine & deliver

        echo "    Release: sendmail -qQ -qI${REPLY:2}"
    done < <( find "$QD" -maxdepth 1 -type f -name "hf*" -printf '%f\n' )

    if [ $FOUND -gt 0 ]; then
        exit 0
    elif [ -z "$CRONJOB" ]; then
        echo "Quarantine is empty"
        exit 1
    else
        exit 1
    fi
fi

# Fallback to mailq

L="`mailq -qQ 2>&1`"
if [ -n "$CRONJOB" ] && echo "$L" | grep -qP '^\s*Total\srequests:\s+0'; then
    exit 0
fi

cat <<EOF
$L
EOF
