#!/bin/bash

# Copyright (C) 2021 Timothe Litt <litt at acm.org>

# Check for non-empty quarantine queue & report

# Locate smqdecode - check same place as this script, then try PATH

SMQ="$(dirname "$0")/smqdecode"
if ! [ -x "$SMQ" ]; then
    SMQ="$(which smqdecode 2>/dev/null)"
fi
QD=

# Look for Queue directory in sendmail.cf, then default

if [[ -n "$SMQ" && -x "$SMQ" ]]; then
    SMCONFIG=
    for DIR in /opt/etc/mail /usr/local/etc/mail /etc/mail; do
        if [ -f "$DIR/sendmail.cf" ]; then
            SMCONFIG="$DIR/sendmail.cf"
            break;
        fi
    done

    if [[ -n "$SMCONFIG" && -f "$SMCONFIG" ]]; then
        QD="$(grep '^O QueueDirectory=' /etc/mail/sendmail.cf | tail -n 1)"
        if [[ "$QD" =~ ^O\ QueueDirectory=(.*)$ ]]; then
            QD="${BASH_REMATCH[1]}"
        else
            QD=
        fi
    fi
    [ -z "$QD" ] && QD="/var/spool/mqueue"
fi

# If have smqdecode && queue directory, look there for quarantined mail

if [[ -n "$QD" && -d "$QD" ]]; then
    FOUND=0
    while read -r ; do
        if [ "$FOUND" == 0 ]; then echo "Quarantined e-mail"; fi
        echo
        ((FOUND++))

        # Extract queue ID

        echo "$QD/$REPLY => ${REPLY:2}"

        # Select interesting headers and indent

        $SMQ --queue=$QD --headers --nobody --nowarn --nometadata "$REPLY" | \
            grep -iP '^(From|Date|To|Subject|Message-ID|X-Virus-Status):'  | \
            sed -e 's/^/    /g'

        # Command to view this e-mail

        echo "    View   : $SMQ --queue=$QD --message --limit-body=none ${REPLY:2} | less"

        # Command to remove from quarantine & delete immediately

        echo "    Delete : $SMQ --queue=$QD --delete ${REPLY:2}"

        # Command to release from quarantine & deliver

        echo "    Release: sendmail -qQ -qI${REPLY:2}"
    done < <( find "$QD" -maxdepth 1 -type f -name "hf*" -printf '%f\n' )

    if [ "$FOUND" -gt 0 ]; then
        exit 0
    elif [ -z "$CRONJOB" ]; then
        echo "Quarantine is empty"
        exit 1
    else
        exit 1
    fi
fi

# Fallback to mailq

L="$(mailq -qQ 2>&1)"
if [ -n "$CRONJOB" ] && grep -qP '^\s*Total\srequests:\s+0' <<<"$L" ; then
    exit 0
fi

cat <<<"$L"
exit
